version: "3.8"

services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=carli
      - N8N_BASIC_AUTH_PASSWORD=✨IntiBot2025
      - N8N_HOST=localhost
      - WEBHOOK_TUNNEL_URL=http://localhost:5678
    volumes:
      - ./n8n_data:/home/node/.n8n

